#move forwarding api service to inbox libs
OpenPaaS-Suite/esn-frontend-inbox pull request #108
Opened 2020-09-03 10:47 UTC by asmaNode

inboxForwardingClient service is required in inbox config in admin modules.
ToDo : delete inboxForwardingClient from unified inbox (not yet)

2020-09-03 13:21 UTC, chamerling requested changes
Bad commit message

2020-09-04 02:28 UTC, piavgh commented
Please add the related issue ID in the commit message and PR message

2020-09-14 02:24 UTC, tuanlc requested changes

2020-09-14 02:24 UTC, tuanlc commented on src/linagora.esn.unifiedinbox/app/components/inbox-configuration/forwardings/inbox-forwardings.controller.js
> +//require('../../../services/forwardings/inbox-forwardings-api-client.service.js');
comment?

2020-09-14 02:24 UTC, tuanlc commented on src/linagora.esn.unifiedinbox/app/components/inbox-configuration/forwardings/inbox-forwardings.controller.js
> +require('../../../../../esn.inbox.libs/app/services/forwarding/inbox-forwardings-api-client.service.js');
no need this since you require the angular module `esn.inbox.lib` module file in app.module

2020-09-14 02:24 UTC, tuanlc commented on src/linagora.esn.unifiedinbox/app/components/inbox-configuration/forwardings/user/inbox-forwardings-user.controller.js
> +//require('../../../../services/forwardings/inbox-forwardings-api-client.service.js');
comment?

2020-09-14 02:24 UTC, tuanlc commented on src/linagora.esn.unifiedinbox/app/components/inbox-configuration/forwardings/user/inbox-forwardings-user.controller.js
> +require('../../../../../../esn.inbox.libs/app/services/forwarding/inbox-forwardings.service.js');
no need this

2020-09-14 13:42 UTC, asmaNode commented
this pr will be replaced by this https://github.com/OpenPaaS-Suite/esn-api-client/pull/19

2020-09-14 13:42 UTC, closed without merging