#48 fix app broken when duplicate emails in the mailto parameter
OpenPaaS-Suite/esn-frontend-inbox pull request #124
Opened 2020-09-08 16:25 UTC by rezk2ll

![image](https://user-images.githubusercontent.com/6764881/92502738-3913be00-f1f8-11ea-8dc9-e5e6ce0b9f2d.png)

2020-09-08 20:58 UTC, MichaelBailly approved these changes

2020-09-09 01:24 UTC, tuanlc submitted a review, later dismissed
Please refactor your commit message to have the correct ticket link that is clickable to redirect to the ticket.

2020-09-09 01:24 UTC, tuanlc commented on src/linagora.esn.unifiedinbox/app/components/composer/composer.controller.js
> +    function _RemoveDuplicateTo(email) {
```suggestion
    function _removeDuplicateRecipients(message) {
```

2020-09-09 01:24 UTC, tuanlc commented on src/linagora.esn.unifiedinbox/app/components/composer/composer.controller.js
> +      _RemoveDuplicateTo(self.message);
Write tests for this

2020-09-09 08:19 UTC, MichaelBailly submitted a review, later dismissed

2020-09-09 08:46 UTC, piavgh reviewed
The commit message should be `OpenPaaS-Suite/esn-frontend-mailto#48...`, not `OpenPaaS-Suite:esn-frontend-mailto#48...`. 
`/`, not `:`

2020-09-09 08:48 UTC, chamerling requested changes

2020-09-09 08:48 UTC, chamerling commented on src/linagora.esn.unifiedinbox/app/components/composer/composer.controller.spec.js
> +    it('should remove duplicate email adresses in the To property', () => {
Should also have a test when there are multiple email values, not only the same as this one

2020-09-09 09:20 UTC, rezk2ll commented
> The commit message should be `OpenPaaS-Suite/esn-frontend-mailto#48...`, not `OpenPaaS-Suite:esn-frontend-mailto#48...`.
> `/`, not `:`

done ty

2020-09-09 09:21 UTC, huy-ta submitted a review, later dismissed

2020-09-09 09:28 UTC, piavgh requested changes
The 2nd commit message is incorrect. It references another issue

2020-09-09 09:48 UTC, tuanlc approved these changes

2020-09-09 10:05 UTC, piavgh approved these changes

2020-09-09 10:33 UTC, merged