OpenPaaS/esn-frontend-admin#67 - Move message-body Component To inbox.libs
OpenPaaS-Suite/esn-frontend-inbox pull request #150
Opened 2020-09-16 10:20 UTC by piavgh

Partially resolves OpenPaaS-Suite/esn-frontend-admin#67

2020-09-16 10:41 UTC, tuanlc requested changes

2020-09-16 10:41 UTC, tuanlc commented on src/all.less
> +@import "./esn.inbox.libs/app/inbox.libs.less";
Please follow the convention for naming:
```suggestion
@import "./esn.inbox.libs/app/app.less";
```

2020-09-17 08:43 UTC, rezk2ll approved these changes

2020-09-17 08:49 UTC, huy-ta approved these changes

2020-09-17 08:54 UTC, merged