#277 Fix incorrect receipient
OpenPaaS-Suite/esn-frontend-inbox pull request #291
Opened 2020-12-16 09:17 UTC by oubchid

2020-12-16 09:28 UTC, rezk2ll commented on src/esn.inbox.libs/app/services/send-email/email-sending.service.js
> +      }
```suggestion
      const notMe = ({ email }) => email !== getEmailAddress(sender);
```

2020-12-16 10:45 UTC, rouazana reviewed
why don't you add any test case about multiple recipient (several to, several cc, several bcc, mixed)?

2020-12-16 11:16 UTC, rezk2ll commented on src/esn.inbox.libs/app/services/send-email/email-sending.service.js
> +        to: _(email.to || []).concat(getReplyToRecipients(email)).uniq('email').value().filter(notMe),
```suggestion
        to: _.uniq([...getReplyToRecipients(email), email.to], 'email').filter(notMe),
```

2020-12-16 12:57 UTC, oubchid commented
> why don't you add any test case about multiple recipient (several to, several cc, several bcc, mixed)?

I will , but first I need the fix the bug then fix the existing tests

2020-12-16 13:09 UTC, oubchid commented
@rouazana we don't need the cc and bcc. this PR should fix only `to` (one recipient or multiple)
usera send a message to userb 
1. we should have userb in `to` when usera reply
usera send a message to userb and userc
2. we should have userb and userc in `to` when usera reply.


should keep all bcc, cc if we reply sush as reply all ?
if yes This PR should also fix bcc, and cc ?

2020-12-16 14:22 UTC, rouazana commented
> should keep all bcc, cc if we `reply` sush as `reply all` ?
> if yes This PR should also fix bcc, and cc ?

If you are asking, this means that these tests are missing :)
In my opinion, yes reply all should be also handled, but it could be in an other ticket

2020-12-17 14:07 UTC, rezk2ll approved these changes

2020-12-22 10:29 UTC, alagane submitted a review, later dismissed

2020-12-22 11:54 UTC, fabienmoyon commented
typo in the commit and the PR title

2020-12-22 11:54 UTC, fabienmoyon requested changes
typo in the commit and the PR title

2020-12-22 13:45 UTC, alagane approved these changes

2020-12-22 14:42 UTC, fabienmoyon approved these changes

2020-12-22 14:43 UTC, merged