#202 Edit mail as new
OpenPaaS-Suite/esn-frontend-inbox pull request #356
Opened 2021-02-17 15:46 UTC by oubchid

2021-02-18 13:42 UTC, fabienmoyon approved these changes

2021-02-18 13:42 UTC, fabienmoyon commented on src/esn.inbox.libs/app/services/send-email/email-sending.service.js
> +        subjectPrefix: 'New: ',
we don't need a prefix for this one ;)

2021-02-18 13:42 UTC, fabienmoyon commented on src/esn.inbox.libs/app/services/send-email/email-sending.service.js
> +        recipients: getReplyRecipients,
As I know it's more a `getReplyAllRecipients` here

2021-02-18 13:42 UTC, fabienmoyon commented on src/esn.inbox.libs/app/services/send-email/email-sending.service.js
> +        referenceIdHeader: INBOX_MESSAGE_HEADERS.FORWARD
`FORWARD` no, it's like a new message

2021-02-18 13:42 UTC, fabienmoyon commented on src/linagora.esn.unifiedinbox/i18n/fr.json
> +  "Edit as New": "Rédaction",
Editer comme un nouveau mail

2021-02-18 13:43 UTC, fabienmoyon approved these changes

2021-02-18 13:43 UTC, fabienmoyon requested changes
need changes

2021-02-23 12:48 UTC, fabienmoyon approved these changes

2021-02-23 14:00 UTC, fabienmoyon approved these changes

2021-02-23 14:00 UTC, fabienmoyon commented on src/esn.inbox.libs/app/services/jmap-item/jmap-item-service.js
> +      emailSendingService.editAsNewEmailObject(message.id, session.user).then(function(replyMessage) {
`replyMessage` to `newMessage`

2021-02-23 14:21 UTC, alagane approved these changes

2021-02-23 19:10 UTC, fabienmoyon approved these changes

2021-02-23 19:10 UTC, merged